on:
  workflow_call:
    inputs:
      is_tag:
        description: "Is a Git Tag"
        type: string
        required: true
      current_branch_tag:
        description: "Git branch or Tag"
        type: string
        required: true
      stable_unstable:
        description: "stable/unstable (currently not used)"
        type: string
        required: true
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true

jobs:
  build-windows-installer:
    name: build-windows-installer
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - name: Build Windows installer
        run: ./ciBuildWindowsInstaller.sh ${{ inputs.is_tag }} ${{ inputs.current_branch_tag }}
        working-directory: ./WindowsInstaller
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}

      - name: Upload Windows installer 32
        uses: actions/upload-artifact@v2
        with:
          name: WindowsInstaller
          path: ./WindowsInstaller/OrthancInstaller-Win32.exe

      - name: Upload Windows installer 64
        uses: actions/upload-artifact@v2
        with:
          name: WindowsInstaller
          path: ./WindowsInstaller/OrthancInstaller-Win64.exe
